version: "3.5"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 8080:8080
    environment:
      - GF_SERVER_HTTP_PORT=8080
    networks:
      - grafana-net
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - grafana-net

networks:
  grafana-net:
    name: host
    external: true

volumes:
  grafana_data: {}
  prometheus_data: {}
